apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: quocbui0607/k8s-task-demo
          env:
            - name: AUTH_ADDRESS
              # value: "10.111.231.44"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks